### PR TITLE
remove field limit. fix python 2.7.6 issue and unicode error

### PR DESCRIPTION
**Pull request by rstalbow**

### CODE REVIEW

**Comment by moneymoy** [comment]
fyi, the removal of the explicit fields list seems to yield a response containing only the id and name. This might be a problem if email is expected elsewhere since it is no longer included in the response.

**Comment by rstalbow** [comment]
@moneymoy Thats not what I experienced when I removed explicit list. For me, when I removed the list I got a lot more data back included

**Comment by moneymoy** [comment]
hmm, I'm guessing FB may be inconsistent in returning things if the fields are not explicitly defined, or maybe FB made a change on their side very recently. But currently, if I go into the fb developer tools -> Graph API Explorer and test things out, it only returns name and id if the fields are not passed in the GET url (generate a user access token for your app, and in the GET field try with and without "?fields=id,name,email").

**Comment by rstalbow** [comment]
@moneymoy just had a look and my app is set to use Facebook api version v2.2. Between v2.3 and v2.4 whats returned by Facebook changes. I guess what needs returning should be a setting? possibly using FACEBOOK_DEFAULT_SCOPE, although I havent looked into what that is used for

**Pull request merged**
